# Configuration
# Google Street View credential and urls
# ------


# ~~~ You should change the followings ~~~
# Your API Key
API: 

# Your Signature Key
Signature: 

# The size of GSV image,  {width}x{height}, Max and Default: 640x640
ImageMaxSize: 640x640


# !!! Don't change the followings !!!
URLHead: https://maps.googleapis.com/maps/api/streetview?
URLMeta: https://maps.googleapis.com/maps/api/streetview/metadata?
